INSERT INTO `collector_company` VALUES ('BU1100', '造纸事业部', 1, 1, 1, 2);
INSERT INTO `collector_company` VALUES ('BU1960', '北美事业部', 1, 1, 3, 3);
INSERT INTO `collector_company` VALUES ('BU2100', '包装事业部', 1, 1, 2, 2);
INSERT INTO `collector_company` VALUES ('E1100', '山鹰国际控股股份公司（母公司）', 1, 1, 1, 2);
INSERT INTO `collector_company` VALUES ('E1110', '浙江山鹰纸业有限公司（母公司）', 0, 1, 1, 2);
INSERT INTO `collector_company` VALUES ('E1120', '山鹰纸业销售有限公司', 0, 0, 1, 2);
INSERT INTO `collector_company` VALUES ('E1130', '马鞍山市天福纸箱纸品有限公司', 0, 0, 1, 2);
INSERT INTO `collector_company` VALUES ('E1140', '山鹰国际控股股份公司上海分公司', 0, 1, 8, 2);
INSERT INTO `collector_company` VALUES ('E1150', '山鹰华中纸业有限公司', 0, 1, 1, 2);
INSERT INTO `collector_company` VALUES ('E1160', '山鹰纸业（重庆）有限公司', 0, 0, 5, 2);
INSERT INTO `collector_company` VALUES ('E1170', '山鹰纸业（福建）有限公司', 0, 0, 5, 2);
INSERT INTO `collector_company` VALUES ('E1180', '山鹰纸业（湖北）有限公司', 0, 0, 5, 2);
INSERT INTO `collector_company` VALUES ('E1190', '福建省联盛纸业有限责任公司（母公司）', 0, 1, 1, 2);
INSERT INTO `collector_company` VALUES ('E1200', '吉安集团有限公司上海分公司', 0, 1, 8, 2);
INSERT INTO `collector_company` VALUES ('E1210', '山鹰纸业（吉林）有限公司', 0, 1, 4, 2);
INSERT INTO `collector_company` VALUES ('E1220', '山鹰纸业（广东）有限公司', 0, 1, 1, 2);
INSERT INTO `collector_company` VALUES ('E1960', 'Global Win Wickliffe LLC', 0, 0, 3, 3);
INSERT INTO `collector_company` VALUES ('E1970', 'Phoenix Paper Wickliffe LLC', 0, 0, 3, 3);
INSERT INTO `collector_company` VALUES ('E2110', '合肥祥恒包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2120', '武汉祥恒包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2130', '合肥华东包装有限公司（母公司）', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2140', '合肥华东包装有限公司武汉分公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2150', '合肥华东包装有限公司芜湖分公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2160', '祥恒（莆田）包装有限公司（母公司）', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2170', '祥恒（厦门）包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2180', '祥恒（天津）包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2190', '四川祥恒包装制品有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2200', '浙江祥恒包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2210', '祥恒（嘉善）包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2220', '苏州山鹰纸业纸品有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2230', '祥恒（杭州）包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2240', '马鞍山祥恒包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2250', '扬州祥恒包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2260', '祥恒（常州）包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2270', '祥恒创意包装有限公司（母公司）', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2280', '青岛恒广泰包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2290', '烟台恒广泰包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2300', '祥恒（中山）包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2310', '无锡新祥恒包装科技有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2320', '中印科技股份有限公司', 0, 0, 5, 2);
INSERT INTO `collector_company` VALUES ('E2330', '陕西祥恒包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2340', '南昌祥恒包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2350', '中祥检测科技有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2360', '中山中健环保包装股份有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2370', '中山市山健包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2380', '广西南宁中健包装有限公司（母公司）', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2390', '南宁胜奕兴业包装有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E2900', '恒健（香港）包装有限公司', 0, 0, 5, 7);
INSERT INTO `collector_company` VALUES ('E2910', '祥恒创意（香港）包装有限公司', 0, 0, 5, 7);
INSERT INTO `collector_company` VALUES ('E3110', '马鞍山市蓝天废旧物资回收有限公司', 0, 0, 1, 2);
INSERT INTO `collector_company` VALUES ('E3120', '上海山鹰供应链管理有限公司', 0, 1, 8, 2);
INSERT INTO `collector_company` VALUES ('E3130', '福建省莆田市阳光纸业有限公司', 0, 0, 1, 2);
INSERT INTO `collector_company` VALUES ('E3140', '福建环宇纸业有限公司', 0, 0, 5, 2);
INSERT INTO `collector_company` VALUES ('E3150', '嘉兴环宇商务服务有限公司', 0, 0, 6, 2);
INSERT INTO `collector_company` VALUES ('E3160', '马鞍山环宇再生资源科技有限公司', 0, 1, 1, 2);
INSERT INTO `collector_company` VALUES ('E3170', '嘉兴环宇再生资源科技有限公司', 0, 0, 6, 2);
INSERT INTO `collector_company` VALUES ('E3190', '浙江泰兴纸业有限公司', 0, 0, 1, 2);
INSERT INTO `collector_company` VALUES ('E3200', '漳州宇盛纸业有限公司', 0, 0, 1, 2);
INSERT INTO `collector_company` VALUES ('E3210', '宇盛（上海）再生资源开发有限公司', 0, 0, 1, 2);
INSERT INTO `collector_company` VALUES ('E3220', '浙江山鹰供应链管理有限公司', 0, 0, 5, 2);
INSERT INTO `collector_company` VALUES ('E3230', '荆州联宇再生资源有限公司', 0, 0, 5, 2);
INSERT INTO `collector_company` VALUES ('E3800', 'Container Transport Oldenburger BV(Consolidation)', 0, 0, 6, 3);
INSERT INTO `collector_company` VALUES ('E3900', '环宇集团国际控股有限公司（母公司）', 1, 0, 6, 3);
INSERT INTO `collector_company` VALUES ('E3910', 'Cycle Link (U.S.A) Inc.', 0, 0, 6, 3);
INSERT INTO `collector_company` VALUES ('E3920', 'Cycle Link Austrlia PTY Ltd', 0, 0, 6, 3);
INSERT INTO `collector_company` VALUES ('E3930', 'Cycle Link (UK) Limited', 0, 0, 6, 3);
INSERT INTO `collector_company` VALUES ('E3940', 'Cycle Link Co.,Ltd.-JPN', 0, 0, 6, 3);
INSERT INTO `collector_company` VALUES ('E3950', 'Cycle Link (Europe) B.V.', 0, 0, 6, 3);
INSERT INTO `collector_company` VALUES ('E4110', '浙江中远发仓储服务有限公司', 0, 0, 2, 2);
INSERT INTO `collector_company` VALUES ('E4120', '马鞍山天顺港口有限责任公司（母公司）', 0, 1, 8, 2);
INSERT INTO `collector_company` VALUES ('E4130', '马鞍山天顺力达集装箱服务有限责任公司', 0, 0, 8, 2);
INSERT INTO `collector_company` VALUES ('E4140', '马鞍山天顺船务代理有限公司', 0, 0, 8, 2);
INSERT INTO `collector_company` VALUES ('E5110', '山鹰（上海）融资租赁有限公司', 0, 1, 8, 2);
INSERT INTO `collector_company` VALUES ('E5130', '谊来（莆田）珠宝工业有限公司', 0, 0, 5, 2);
INSERT INTO `collector_company` VALUES ('E5200', '山鹰投资管理有限公司（母公司）', 0, 1, 8, 2);
INSERT INTO `collector_company` VALUES ('E5210', '深圳前海山鹰原力基金管理有限公司', 0, 0, 5, 2);
INSERT INTO `collector_company` VALUES ('E5220', '深圳前海山鹰新时代投资管理有限公司', 0, 0, 8, 2);
INSERT INTO `collector_company` VALUES ('E5230', '马鞍山市雄鹰新兴产业投资基金（有限合伙）', 0, 0, 8, 2);
INSERT INTO `collector_company` VALUES ('E5240', '安徽省鹰隼恒富一期新兴产业基金（有限合伙）', 0, 0, 8, 2);
INSERT INTO `collector_company` VALUES ('E5250', '安徽省鹰隼恒富二期新兴产业基金（有限合伙）', 0, 0, 8, 2);
INSERT INTO `collector_company` VALUES ('E5260', '深圳前海山鹰新时代新兴产业发展基金合伙企业（有限合伙）', 0, 0, 8, 2);
INSERT INTO `collector_company` VALUES ('E5270', '深圳前海山鹰新时代新兴产业二号发展基金合伙企业（有限合伙）', 0, 0, 8, 2);
INSERT INTO `collector_company` VALUES ('E5280', '云印技术（深圳）有限公司', 1, 1, 9, 2);
INSERT INTO `collector_company` VALUES ('E5290', '深圳市云印电子商务有限公司', 0, 0, 9, 2);
INSERT INTO `collector_company` VALUES ('E5300', '宁波市云印微供电子商务有限公司', 0, 0, 9, 2);
INSERT INTO `collector_company` VALUES ('E5310', '深圳市云印商业保理有限公司', 0, 0, 9, 2);
INSERT INTO `collector_company` VALUES ('E5320', '厦门包印通科技有限公司', 0, 0, 5, 2);
INSERT INTO `collector_company` VALUES ('E5900', 'Global win co.,ltd（母公司）', 0, 0, 5, 3);
INSERT INTO `collector_company` VALUES ('E5910', 'Global win capital corporation', 0, 0, 3, 3);
INSERT INTO `collector_company` VALUES ('E6120', '爱拓环保能源（浙江）有限公司', 0, 1, 4, 2);
INSERT INTO `collector_company` VALUES ('E6130', '山鹰（上海）企业管理咨询有限公司', 0, 1, 8, 2);
INSERT INTO `collector_company` VALUES ('E6140', '嘉兴路通报关有限公司', 0, 0, 1, 2);
INSERT INTO `collector_company` VALUES ('E6150', '宁波环深垃圾分类服务有限公司', 0, 0, 1, 2);
INSERT INTO `collector_company` VALUES ('ENP', 'SUTRIV Holding AB（合并）', 1, 1, 7, 6);
